### ISSUE TITLE
SNS topic subscription isn't confirmed after being created

### ISSUE THREAD

**Issue by tiagobrito** [uecode/qpush-bundle#102] opened 2016-06-20 13:18 UTC
I've tried without success to create and subscribe to SNS with AWS provider.
Can you confirm that this is still working?

**Comment by kmfk** [comment] 2016-06-20 22:08
Hey @tiagobrito, can you be specific?  Is it not *creating* the topic, not *subscribing* to a created topic, or just not doing either?

Are you testing locally?  In order for a topic to be subscribed to, it needs to be an endpoint that is publicly available so that SNS can send a POST to that endpoint for subscription confirmation.  If its not publicly available, the subscription won't work.

You can use Ngrok as mentioned in the docs in that case to allow for testing locally.

**Comment by tiagobrito** [comment] 2016-06-22 23:34
@kmfk Thanks for your quick reply.
I have investigated more and reach to the conclusion that the topic is being created and subscribed but it isn't confirmed. Is there a way to automatic confirm the subscribed of each topic ? or I'm missing something ?
Thanks in advance ;)

**Comment by kmfk** [comment] 2016-06-22 23:42
@tiagobrito Are you doing this locally?  As mentioned above, the http(s) endpoint you specify needs to be publicly accessible.  

When you subscribe an endpoint to a topic, SNS will automatically send a confirmation request (POST request) and you'd need to respond with a request to a given url to confirm. That process is handled with you in this library, as long as SNS can reach your endpoint to begin with.  To be clear, _your endpoint must be accessible by SNS_.

In local development, you typically do not have a public url unless you use something like ngrok.  See: http://qpush-bundle.readthedocs.io/en/latest/usage.html#push-queues-in-development

**Comment by tiagobrito** [comment] 2016-06-22 23:55
Yes, I'm doing this locally, but the thing is: the request from SNS never reached my ngrok (but I will double check this).

**Comment by tiagobrito** [comment] 2016-06-23 09:41
I don't get it... I always get ```PendingConfirmation``` for the ngrok subscription, and the post is in the ngrok HTTP request list.
In sns endpoint I have to have a route and a controller, do I need to return something specific in this controller ?

**Comment by tiagobrito** [comment] 2016-06-23 16:19
I think i finally got it...

My queue my_queue_key is different from my queue name in configurations.

In RequestListener when the type is _Notification_, the queue name is getted from the subject:
```$queue = $notification['Subject'];```` (which is equal to _my_queue_key_ )

but on the other side when the type is _SubscriptionConfirmation_:
```$queue = str_replace('qpush_', '', $last);``` (which is equal to queue name that isn't equal to _my_queue_key_ and the onNotification method won't be trigger on AwsProvider)

**Comment by kmfk** [comment] 2016-06-30 21:28
Thanks for looking into that @tiagobrito - just merged in a fix that should work for when the `queue_name` is used that will still allow subscriptions to work as intended.

**Closed by kmfk** 2016-06-30 21:28 UTC
